import { View, Text, Image, TouchableOpacity, StyleSheet, FlatList, ActivityIndicator, Modal, TextInput, Button } from 'react-native';
import React, { useState, useEffect } from 'react';
import * as ImagePicker from 'expo-image-picker';
import { LinearGradient } from 'expo-linear-gradient';
import axios from 'axios';

const url = "https://unimate-backend.onrender.com/";

const Announcements = () => {
  const [announcements, setAnnouncements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isAdmin, setIsAdmin] = useState(true);
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [newAnnouncement, setNewAnnouncement] = useState({
    photo: '',
    message: '',
  });
  const [selectedImage, setSelectedImage] = useState(null);

  useEffect(() => {
    // Fetch announcements from backend
    const fetchAnnouncements = async () => {
      try {
        const response = await axios.get(url + 'announcement/all'); 
        setAnnouncements(response.data);
      } catch (error) {
        console.error('Error fetching announcements:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchAnnouncements();
  }, []);

  const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
      base64: true,
    });

    if (!result.canceled) {
      const base64Image = `data:image/jpeg;base64,${result.assets[0].base64}`;
      setSelectedImage(base64Image);
      setNewAnnouncement({ ...newAnnouncement, photo: base64Image });
    }
  };

  const handleAddAnnouncement = async () => {
    const newAnn = {
      ...newAnnouncement,
      _id: (announcements.length + 1).toString(), // ID should be generated by the backend ideally
      timestamp: new Date().toISOString(),
      photo: selectedImage || 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==',
    };

    try {
      await axios.post(url + 'announcement/create', newAnn); 
      setAnnouncements([newAnn, ...announcements]);
    } catch (error) {
      console.error('Error adding announcement:', error);
    }

    setNewAnnouncement({ photo: '', message: '' });
    setSelectedImage(null);
    handleCloseModal();
  };

  const handleCloseModal = () => {
    setIsModalVisible(false);
  };

  if (loading) {
    return <ActivityIndicator size="large" color="#ffffff" style={styles.loading} />;
  }

  return (
    <LinearGradient
      colors={['#FFA500', '#D85401', '#1A1A1A']}
      style={styles.gradient}
      start={{ x: -2.7, y: -0.7 }}
      end={{ x: 0.2, y: 0.6 }}
    >
      <View style={styles.container}>
        <Text style={styles.title}>Announcements</Text>

        {isAdmin && (
          <TouchableOpacity style={styles.createButton} onPress={() => setIsModalVisible(true)}>
            <Text style={styles.createButtonText}>+</Text>
          </TouchableOpacity>
        )}

        <FlatList
          data={announcements}
          renderItem={({ item }) => (
            <View style={styles.announcement}>
              <Image source={{ uri: item.photo }} style={styles.photo} />
              <View style={styles.content}>
                <Text style={styles.message}>{item.message}</Text>
                <Text style={styles.timestamp}>{new Date(item.timestamp).toLocaleString()}</Text>
              </View>
            </View>
          )}
          keyExtractor={(item) => item._id}
        />

        <Modal
          visible={isModalVisible}
          transparent={true}
          animationType="slide"
          onRequestClose={handleCloseModal}
        >
          <View style={styles.modalContainer}>
            <View style={styles.modalContent}>
              <Text style={styles.modalTitle}>Add New Announcement</Text>
              <TouchableOpacity style={styles.imagePickerButton} onPress={pickImage}>
                <Text style={styles.imagePickerText}>Pick an image</Text>
              </TouchableOpacity>
              {selectedImage && (
                <Image source={{ uri: selectedImage }} style={styles.selectedImage} />
              )}
              <TextInput
                style={styles.input}
                placeholder="Message"
                value={newAnnouncement.message}
                onChangeText={(text) => setNewAnnouncement({ ...newAnnouncement, message: text })}
                multiline
              />
              <Button title="Add Announcement" onPress={handleAddAnnouncement} />
              <Button title="Cancel" onPress={handleCloseModal} color="red" />
            </View>
          </View>
        </Modal>
      </View>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 20,
    top: 15,
  },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    textAlign: 'center',
    marginBottom: 20,
  },
  announcement: {
    marginBottom: 20,
    backgroundColor: '#1e1e1e',
    borderRadius: 10,
    overflow: 'hidden',
  },
  photo: {
    width: '100%',
    height: 200,
    borderRadius: 10,
  },
  content: {
    padding: 10,
  },
  message: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 10,
  },
  timestamp: {
    fontSize: 14,
    color: '#888',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButton: {
    backgroundColor: '#D85401',
    width: 40,
    height: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    position: 'absolute',
    bottom: 20,
    right: 20,
    zIndex: 1,
  },
  createButtonText: {
    top: -5,
    color: '#fff',
    fontSize: 35,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#1e1e1e',
    padding: 20,
    borderRadius: 10,
  },
  modalTitle: {
    fontSize: 20,
    color: '#fff',
    marginBottom: 10,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
  },
  imagePickerButton: {
    backgroundColor: '#444',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
    alignItems: 'center',
  },
  imagePickerText: {
    color: '#fff',
  },
  selectedImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginBottom: 10,
  },
});

export default Announcements;
